# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-platform
  #REPOSITORY: ghcr.io/adrianliechti/wingman-platform:nightly

tasks:
  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}

  server:
    dotenv: ['.env' ]
    
    cmds:
      - go run cmd/server/main.go

  client:
    cmds:
      - go run cmd/client/main.go
  
  run:
    cmds:
      - docker compose up --remove-orphans --force-recreate
  
  lgtm:
    cmds:
      - docker run -it --rm -p 3000:3000 -p 4317:4317 -p 4318:4318 grafana/otel-lgtm