// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: researcher.proto

package custom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Researcher_Research_FullMethodName = "/researcher.Researcher/Research"
)

// ResearcherClient is the client API for Researcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResearcherClient interface {
	Research(ctx context.Context, in *ResearchRequest, opts ...grpc.CallOption) (*ResearchResponse, error)
}

type researcherClient struct {
	cc grpc.ClientConnInterface
}

func NewResearcherClient(cc grpc.ClientConnInterface) ResearcherClient {
	return &researcherClient{cc}
}

func (c *researcherClient) Research(ctx context.Context, in *ResearchRequest, opts ...grpc.CallOption) (*ResearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResearchResponse)
	err := c.cc.Invoke(ctx, Researcher_Research_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResearcherServer is the server API for Researcher service.
// All implementations must embed UnimplementedResearcherServer
// for forward compatibility.
type ResearcherServer interface {
	Research(context.Context, *ResearchRequest) (*ResearchResponse, error)
	mustEmbedUnimplementedResearcherServer()
}

// UnimplementedResearcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResearcherServer struct{}

func (UnimplementedResearcherServer) Research(context.Context, *ResearchRequest) (*ResearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Research not implemented")
}
func (UnimplementedResearcherServer) mustEmbedUnimplementedResearcherServer() {}
func (UnimplementedResearcherServer) testEmbeddedByValue()                    {}

// UnsafeResearcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResearcherServer will
// result in compilation errors.
type UnsafeResearcherServer interface {
	mustEmbedUnimplementedResearcherServer()
}

func RegisterResearcherServer(s grpc.ServiceRegistrar, srv ResearcherServer) {
	// If the following call pancis, it indicates UnimplementedResearcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Researcher_ServiceDesc, srv)
}

func _Researcher_Research_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearcherServer).Research(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Researcher_Research_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearcherServer).Research(ctx, req.(*ResearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Researcher_ServiceDesc is the grpc.ServiceDesc for Researcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Researcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "researcher.Researcher",
	HandlerType: (*ResearcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Research",
			Handler:    _Researcher_Research_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "researcher.proto",
}
