// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: researcher.proto

package custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instructions  string                 `protobuf:"bytes,1,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchRequest) Reset() {
	*x = ResearchRequest{}
	mi := &file_researcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchRequest) ProtoMessage() {}

func (x *ResearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_researcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchRequest.ProtoReflect.Descriptor instead.
func (*ResearchRequest) Descriptor() ([]byte, []int) {
	return file_researcher_proto_rawDescGZIP(), []int{0}
}

func (x *ResearchRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type ResearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchResponse) Reset() {
	*x = ResearchResponse{}
	mi := &file_researcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchResponse) ProtoMessage() {}

func (x *ResearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_researcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchResponse.ProtoReflect.Descriptor instead.
func (*ResearchResponse) Descriptor() ([]byte, []int) {
	return file_researcher_proto_rawDescGZIP(), []int{1}
}

func (x *ResearchResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_researcher_proto protoreflect.FileDescriptor

const file_researcher_proto_rawDesc = "" +
	"\n" +
	"\x10researcher.proto\x12\n" +
	"researcher\"5\n" +
	"\x0fResearchRequest\x12\"\n" +
	"\finstructions\x18\x01 \x01(\tR\finstructions\",\n" +
	"\x10ResearchResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2U\n" +
	"\n" +
	"Researcher\x12G\n" +
	"\bResearch\x12\x1b.researcher.ResearchRequest\x1a\x1c.researcher.ResearchResponse\"\x00B?Z=github.com/adrianliechti/wingman/pkg/researcher/custom;customb\x06proto3"

var (
	file_researcher_proto_rawDescOnce sync.Once
	file_researcher_proto_rawDescData []byte
)

func file_researcher_proto_rawDescGZIP() []byte {
	file_researcher_proto_rawDescOnce.Do(func() {
		file_researcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_researcher_proto_rawDesc), len(file_researcher_proto_rawDesc)))
	})
	return file_researcher_proto_rawDescData
}

var file_researcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_researcher_proto_goTypes = []any{
	(*ResearchRequest)(nil),  // 0: researcher.ResearchRequest
	(*ResearchResponse)(nil), // 1: researcher.ResearchResponse
}
var file_researcher_proto_depIdxs = []int32{
	0, // 0: researcher.Researcher.Research:input_type -> researcher.ResearchRequest
	1, // 1: researcher.Researcher.Research:output_type -> researcher.ResearchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_researcher_proto_init() }
func file_researcher_proto_init() {
	if File_researcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_researcher_proto_rawDesc), len(file_researcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_researcher_proto_goTypes,
		DependencyIndexes: file_researcher_proto_depIdxs,
		MessageInfos:      file_researcher_proto_msgTypes,
	}.Build()
	File_researcher_proto = out.File
	file_researcher_proto_goTypes = nil
	file_researcher_proto_depIdxs = nil
}
