// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: guard.proto

package custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_guard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_guard_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flagged       bool                   `protobuf:"varint,1,opt,name=flagged,proto3" json:"flagged,omitempty"`
	Categories    []*Category            `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_guard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_guard_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

func (x *CheckResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_guard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_guard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_guard_proto_rawDescGZIP(), []int{2}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_guard_proto protoreflect.FileDescriptor

const file_guard_proto_rawDesc = "" +
	"\n" +
	"\vguard.proto\x12\x05guard\"\"\n" +
	"\fCheckRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"Z\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aflagged\x18\x01 \x01(\bR\aflagged\x12/\n" +
	"\n" +
	"categories\x18\x02 \x03(\v2\x0f.guard.CategoryR\n" +
	"categories\"4\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score2=\n" +
	"\x05Guard\x124\n" +
	"\x05Check\x12\x13.guard.CheckRequest\x1a\x14.guard.CheckResponse\"\x00B:Z8github.com/adrianliechti/wingman/pkg/guard/custom;customb\x06proto3"

var (
	file_guard_proto_rawDescOnce sync.Once
	file_guard_proto_rawDescData []byte
)

func file_guard_proto_rawDescGZIP() []byte {
	file_guard_proto_rawDescOnce.Do(func() {
		file_guard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guard_proto_rawDesc), len(file_guard_proto_rawDesc)))
	})
	return file_guard_proto_rawDescData
}

var file_guard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_guard_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: guard.CheckRequest
	(*CheckResponse)(nil), // 1: guard.CheckResponse
	(*Category)(nil),      // 2: guard.Category
}
var file_guard_proto_depIdxs = []int32{
	2, // 0: guard.CheckResponse.categories:type_name -> guard.Category
	0, // 1: guard.Guard.Check:input_type -> guard.CheckRequest
	1, // 2: guard.Guard.Check:output_type -> guard.CheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_guard_proto_init() }
func file_guard_proto_init() {
	if File_guard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guard_proto_rawDesc), len(file_guard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guard_proto_goTypes,
		DependencyIndexes: file_guard_proto_depIdxs,
		MessageInfos:      file_guard_proto_msgTypes,
	}.Build()
	File_guard_proto = out.File
	file_guard_proto_goTypes = nil
	file_guard_proto_depIdxs = nil
}
