// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: segmenter.proto

package custom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Segmenter_Segment_FullMethodName = "/segmenter.Segmenter/Segment"
)

// SegmenterClient is the client API for Segmenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmenterClient interface {
	Segment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error)
}

type segmenterClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmenterClient(cc grpc.ClientConnInterface) SegmenterClient {
	return &segmenterClient{cc}
}

func (c *segmenterClient) Segment(ctx context.Context, in *SegmentRequest, opts ...grpc.CallOption) (*SegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SegmentResponse)
	err := c.cc.Invoke(ctx, Segmenter_Segment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SegmenterServer is the server API for Segmenter service.
// All implementations must embed UnimplementedSegmenterServer
// for forward compatibility.
type SegmenterServer interface {
	Segment(context.Context, *SegmentRequest) (*SegmentResponse, error)
	mustEmbedUnimplementedSegmenterServer()
}

// UnimplementedSegmenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSegmenterServer struct{}

func (UnimplementedSegmenterServer) Segment(context.Context, *SegmentRequest) (*SegmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Segment not implemented")
}
func (UnimplementedSegmenterServer) mustEmbedUnimplementedSegmenterServer() {}
func (UnimplementedSegmenterServer) testEmbeddedByValue()                   {}

// UnsafeSegmenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmenterServer will
// result in compilation errors.
type UnsafeSegmenterServer interface {
	mustEmbedUnimplementedSegmenterServer()
}

func RegisterSegmenterServer(s grpc.ServiceRegistrar, srv SegmenterServer) {
	// If the following call pancis, it indicates UnimplementedSegmenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Segmenter_ServiceDesc, srv)
}

func _Segmenter_Segment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SegmenterServer).Segment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Segmenter_Segment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SegmenterServer).Segment(ctx, req.(*SegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Segmenter_ServiceDesc is the grpc.ServiceDesc for Segmenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Segmenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "segmenter.Segmenter",
	HandlerType: (*SegmenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Segment",
			Handler:    _Segmenter_Segment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "segmenter.proto",
}
