// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: summarizer.proto

package custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_summarizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_summarizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_summarizer_proto_rawDescGZIP(), []int{0}
}

func (x *SummarizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_summarizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_summarizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_summarizer_proto_rawDescGZIP(), []int{1}
}

func (x *Summary) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_summarizer_proto protoreflect.FileDescriptor

const file_summarizer_proto_rawDesc = "" +
	"\n" +
	"\x10summarizer.proto\x12\n" +
	"summarizer\"&\n" +
	"\x10SummarizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1d\n" +
	"\aSummary\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2N\n" +
	"\n" +
	"Summarizer\x12@\n" +
	"\tSummarize\x12\x1c.summarizer.SummarizeRequest\x1a\x13.summarizer.Summary\"\x00B?Z=github.com/adrianliechti/wingman/pkg/summarizer/custom;customb\x06proto3"

var (
	file_summarizer_proto_rawDescOnce sync.Once
	file_summarizer_proto_rawDescData []byte
)

func file_summarizer_proto_rawDescGZIP() []byte {
	file_summarizer_proto_rawDescOnce.Do(func() {
		file_summarizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_summarizer_proto_rawDesc), len(file_summarizer_proto_rawDesc)))
	})
	return file_summarizer_proto_rawDescData
}

var file_summarizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_summarizer_proto_goTypes = []any{
	(*SummarizeRequest)(nil), // 0: summarizer.SummarizeRequest
	(*Summary)(nil),          // 1: summarizer.Summary
}
var file_summarizer_proto_depIdxs = []int32{
	0, // 0: summarizer.Summarizer.Summarize:input_type -> summarizer.SummarizeRequest
	1, // 1: summarizer.Summarizer.Summarize:output_type -> summarizer.Summary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_summarizer_proto_init() }
func file_summarizer_proto_init() {
	if File_summarizer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_summarizer_proto_rawDesc), len(file_summarizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_summarizer_proto_goTypes,
		DependencyIndexes: file_summarizer_proto_depIdxs,
		MessageInfos:      file_summarizer_proto_msgTypes,
	}.Build()
	File_summarizer_proto = out.File
	file_summarizer_proto_goTypes = nil
	file_summarizer_proto_depIdxs = nil
}
