package kreuzberg

import (
	"net/http"
)

var SupportedExtensions = []string{
	".pdf",

	".txt",
	".md",
	".markdown",
	".commonmark",
	".mdx",
	".djot",

	".doc",
	".docx",
	".docm",
	".dot",
	".dotx",
	".dotm",
	".xls",
	".xlsx",
	".xlsm",
	".xlsb",
	".xlam",
	".xla",
	".xltx",
	".xlt",
	".ppt",
	".pptx",
	".pptm",
	".ppsx",
	".pot",
	".potx",
	".potm",

	".odt",
	".ods",
	".dbf",
	".hwp",
	".hwpx",

	".png",
	".jpg",
	".jpeg",
	".gif",
	".webp",
	".bmp",
	".tiff",
	".tif",
	".jp2",
	".j2k",
	".j2c",
	".jpx",
	".jpm",
	".mj2",
	".jbig2",
	".jb2",
	".pnm",
	".pbm",
	".pgm",
	".ppm",

	".html",
	".htm",
	".xml",
	".svg",
	".json",
	".jsonl",
	".ndjson",
	".yaml",
	".yml",
	".toml",
	".csv",
	".tsv",

	".rst",
	".org",
	".rtf",

	".eml",
	".msg",
	".pst",

	".zip",
	".tar",
	".tgz",
	".gz",
	".7z",

	".epub",
	".tex",
	".latex",
	".bib",
	".typst",
	".typ",
	".ipynb",
	".fb2",
	".docbook",
	".dbk",
	".docbook4",
	".docbook5",
	".jats",
	".opml",
	".ris",
	".enw",
	".nbib",

	".pages",
	".numbers",
	".key",
}

var SupportedMimeTypes = []string{
	"application/pdf",

	"application/msword",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"application/vnd.ms-word.document.macroenabled.12",
	"application/vnd.openxmlformats-officedocument.wordprocessingml.template",
	"application/vnd.ms-word.template.macroenabled.12",
	"application/vnd.ms-excel",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"application/vnd.ms-excel.sheet.macroenabled.12",
	"application/vnd.ms-excel.sheet.binary.macroenabled.12",
	"application/vnd.ms-excel.addin.macroenabled.12",
	"application/vnd.ms-excel.template.macroenabled.12",
	"application/vnd.openxmlformats-officedocument.spreadsheetml.template",
	"application/vnd.ms-powerpoint",
	"application/vnd.openxmlformats-officedocument.presentationml.presentation",
	"application/vnd.ms-powerpoint.presentation.macroenabled.12",
	"application/vnd.openxmlformats-officedocument.presentationml.slideshow",
	"application/vnd.openxmlformats-officedocument.presentationml.template",
	"application/vnd.ms-powerpoint.template.macroenabled.12",

	"application/vnd.oasis.opendocument.text",
	"application/vnd.oasis.opendocument.spreadsheet",
	"application/x-dbf",
	"application/dbase",
	"application/x-hwp",
	"application/haansofthwpx",
	"application/x-iwork-pages-sffpages",
	"application/x-iwork-numbers-sffnumbers",
	"application/x-iwork-keynote-sffkey",

	"application/epub+zip",
	"application/x-epub+zip",
	"application/vnd.epub+zip",

	"image/png",
	"image/jpeg",
	"image/jpg",
	"image/pjpeg",
	"image/gif",
	"image/webp",
	"image/bmp",
	"image/x-bmp",
	"image/x-ms-bmp",
	"image/tiff",
	"image/x-tiff",
	"image/jp2",
	"image/jpx",
	"image/jpm",
	"image/mj2",
	"image/x-jbig2",
	"image/x-portable-anymap",
	"image/x-portable-bitmap",
	"image/x-portable-graymap",
	"image/x-portable-pixmap",

	"text/html",
	"application/xhtml+xml",
	"application/xml",
	"text/xml",
	"image/svg+xml",
	"application/json",
	"text/json",
	"application/csl+json",
	"application/x-ndjson",
	"application/jsonl",
	"application/x-jsonlines",
	"application/x-yaml",
	"application/yaml",
	"text/yaml",
	"text/x-yaml",
	"application/toml",
	"text/toml",
	"text/csv",
	"text/tab-separated-values",
	"text/plain",
	"text/troff",
	"text/x-mdoc",
	"text/x-pod",
	"text/x-dokuwiki",
	"text/markdown",
	"text/x-markdown",
	"text/x-commonmark",
	"text/x-gfm",
	"text/x-markdown-extra",
	"text/x-multimarkdown",
	"text/x-rst",
	"text/prs.fallenstein.rst",
	"text/x-org",
	"text/org",
	"application/x-org",
	"application/rtf",
	"text/rtf",
	"text/x-djot",
	"text/djot",
	"text/mdx",
	"text/x-mdx",
	"text/x-source-code",

	"message/rfc822",
	"application/vnd.ms-outlook",
	"application/vnd.ms-outlook-pst",

	"application/zip",
	"application/x-zip-compressed",
	"application/x-tar",
	"application/tar",
	"application/x-gtar",
	"application/x-ustar",
	"application/gzip",
	"application/x-gzip",
	"application/x-7z-compressed",

	"application/x-latex",
	"text/x-tex",
	"application/x-bibtex",
	"text/x-bibtex",
	"application/x-biblatex",
	"application/x-typst",
	"text/x-typst",
	"application/x-ipynb+json",
	"application/x-fictionbook+xml",
	"application/x-fictionbook",
	"text/x-fictionbook",
	"application/xml+opml",
	"application/docbook+xml",
	"text/docbook",
	"application/x-jats+xml",
	"text/jats",
	"application/x-opml+xml",
	"text/x-opml",
	"application/x-research-info-systems",
	"application/x-endnote+xml",
	"application/x-pubmed",
}

type Option func(*Client)

func WithClient(client *http.Client) Option {
	return func(c *Client) {
		c.client = client
	}
}

func WithToken(token string) Option {
	return func(c *Client) {
		c.token = token
	}
}
