// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: translator.proto

package custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_translator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type Translation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Translation) Reset() {
	*x = Translation{}
	mi := &file_translator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Translation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Translation) ProtoMessage() {}

func (x *Translation) ProtoReflect() protoreflect.Message {
	mi := &file_translator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Translation.ProtoReflect.Descriptor instead.
func (*Translation) Descriptor() ([]byte, []int) {
	return file_translator_proto_rawDescGZIP(), []int{1}
}

func (x *Translation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_translator_proto protoreflect.FileDescriptor

const file_translator_proto_rawDesc = "" +
	"\n" +
	"\x10translator.proto\x12\n" +
	"translator\"B\n" +
	"\x10TranslateRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"!\n" +
	"\vTranslation\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2R\n" +
	"\n" +
	"Translator\x12D\n" +
	"\tTranslate\x12\x1c.translator.TranslateRequest\x1a\x17.translator.Translation\"\x00B?Z=github.com/adrianliechti/wingman/pkg/translator/custom;customb\x06proto3"

var (
	file_translator_proto_rawDescOnce sync.Once
	file_translator_proto_rawDescData []byte
)

func file_translator_proto_rawDescGZIP() []byte {
	file_translator_proto_rawDescOnce.Do(func() {
		file_translator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)))
	})
	return file_translator_proto_rawDescData
}

var file_translator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_translator_proto_goTypes = []any{
	(*TranslateRequest)(nil), // 0: translator.TranslateRequest
	(*Translation)(nil),      // 1: translator.Translation
}
var file_translator_proto_depIdxs = []int32{
	0, // 0: translator.Translator.Translate:input_type -> translator.TranslateRequest
	1, // 1: translator.Translator.Translate:output_type -> translator.Translation
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_translator_proto_init() }
func file_translator_proto_init() {
	if File_translator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translator_proto_rawDesc), len(file_translator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translator_proto_goTypes,
		DependencyIndexes: file_translator_proto_depIdxs,
		MessageInfos:      file_translator_proto_msgTypes,
	}.Build()
	File_translator_proto = out.File
	file_translator_proto_goTypes = nil
	file_translator_proto_depIdxs = nil
}
